### ISSUE TITLE
Multiple LogManagers when 404 in IIS

### ISSUE THREAD

**Issue by johncrim** [logjam2/logjam#22]
This error does not occur when running under OwinHost; however when running under IIS, and when a 404 occurs (this doesn't occur during normal Web API or OWIN request handling), a second LogManager is created.

This is causing this error (only seen during 404s):

```
29>  10:38:52.845  GET  http://foo.com/js/app.js.map
     Cache-Control: no-cache
     Connection: keep-alive
     Accept-Encoding: gzip, deflate
     Accept-Language: en-US,en;q=0.9
     User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3212.4 Safari/537.36
     DNT: 1

   10:38:52.932  Error    M.O.Diagnostics.ErrorPageMiddleware   The error page caught the following Exception:
      System.ArgumentException: An item with the same key has already been added.
         at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
         at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
         at Microsoft.Owin.Host.SystemWeb.CallEnvironment.AspNetDictionary.System.Collections.Generic.IDictionary<System.String,System.Object>.Add(String key, Object value)
         at Microsoft.Owin.OwinContextExtensions.SetLogManager(IOwinContext owinContext, LogManager logManager)
         at LogJam.Owin.LogJamManagerMiddleware.Invoke(IOwinContext owinContext)
         at Microsoft.Owin.Host.SystemWeb.OwinCallContext.Execute()
         at Microsoft.Owin.Host.SystemWeb.OwinHttpHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object extraData)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Tv.Base.Web.Owin.AppSettingsMiddleware.<Invoke>d__11.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Web.Http.Owin.HttpMessageHandlerAdapter.<InvokeCore>d__0.MoveNext()
```

For starters, `LogJamManagerMiddleware` should NOT cause this exception. However, it's occurring due to a case that should never occur - the only reasonable explanations for this error are:

1. `LogJamManagerMiddleware` is registered 2x in one pipeline, which should not be possible
2. 2 pipelines are being built, and the same OwinContext is passed to both

**Comment by johncrim** [comment]
57db596 adds a fix to protect against adding a `LogManager` or a `TraceManager` to an `IOwinContext` when the owin context already has them. It also adds tracing of warning or errors: warning if the same instance is added twice; error if different instances are added. In both cases, the original `LogManager` and `TraceManager` is left.

**Comment by johncrim** [comment]
From deploying 57db596, it appears that different `LogManager` and `TraceManager` instances are added to the same `IOwinContext` - it is NOT the case that the same `LogManager` and `TraceManager` instances are added more than once.

It is also resulting in multiple log files (1 per LogManager). The primary log file has all the other expected contents. The 2nd log file is opened when the 404 occurs, and it only contains Startup logging and the 404 request. Both log files contain the 404 request, but only the first log file contains non 404 requests.

This can only be explained by IIS creating a second OWIN pipeline when the first pipeline returns a 404.

**Comment by johncrim** [comment]
To summarize - this issue was an exception that the OwinMiddleware shouldn't have caused, that occurs only when 2 OWIN pipelines are created that share the same `IOwinContext` (request) object.

The flow goes something like the following (as far as I've been able to deduce):

1. Webapp starts, IIS loads the `Microsoft.Owin.Host.SystemWeb.OwinHttpHandler`, which calls the app OwinStartup method, which initializes the OWIN pipeline. The OwinStartup method calls 
2. Some time later, IIS Request arrives for /path_not_exists
3. IIS delegates request to the `Microsoft.Owin.Host.SystemWeb.OwinHttpHandler` filter, which creates a new `IOwinRequest` which wraps the IIS request, and passes it into the OWIN pipeline created in step 1 by the OwinStartup method
4. When using LogJam.Owin, an early middleware (`LogJamManagerMiddleware`) is used to store the webapp's `LogManager` and `ITracerFactory` in the `IOwinContext.Environment` dictionary.
5. No OWIN handler matches the path, so at the end of the pipeline the terminating OWIN handler is called, which sets the response to 404, and apparently sets a switch in the IOwinContext telling the `Microsoft.Owin.Host.SystemWeb.OwinHttpHandler` that no app supplied handler was invoked.
6. The request is returned through the OWIN pipeline back to the `Microsoft.Owin.Host.SystemWeb.OwinHttpHandler` (with 404 set)
7. At this point, presumably b/c the switch was set in step 4, IIS or `Microsoft.Owin.Host.SystemWeb.OwinHttpHandler` goes looking for another handler for the unmatches request.
8. A new OWIN pipeline is created by calling the application OwinStartup method a second time (which repeats the work done in step 1). This creates a new `LogManager` and `TracerFactory`, which creates a new log file if file logging is configured. The same `IOwinRequest` created in step 3 is passed to this new OWIN pipeline.
9. The `LogJamManagerMiddleware` is called in the new pipeline, and the new `LogManager` and `ITracerFactory` are stored in the `IOwinContext.Environment` dictionary. Previously this threw an `ArgumentException` which resulted in the OWIN error page (or whatever other exception handling the application installed); as of LogJam.Owin 1.0.6 and later, no exception is thrown, the existing `LogManager` and `ITracerFactory` stored in the `IOwinContext` remain, and an error is traced in the first pipeline's `ITracerFactory` specifying that a new `LogManager` or `ITracerFactory` are being stored.
10. If using LogJam 1.0.6 and later, the end of the OWIN pipeline is reached, which sets the response status to 404.
11. IIS sends the response from the second OWIN pipeline in the response to the request that arrived in step 2.

The fix in LogJam.Owin 1.0.6 prevents the exception in step 9 which returns the error page (or other error handling). However 2 log files can still be created (if log file names are based on the time of creation) due to 2 calls to the OwinStartup method. The preferred fix is to prevent a second OWIN pipeline from starting.

There may be better fixes, but one approach that works is to add a termination handler to the end of the OWIN pipeline. This can be done as follows:

```
public class Startup
{
	/// <summary>
	/// Configure all the OWIN modules that participate in each request.
	/// </summary>
	public void Configuration(IAppBuilder owinAppBuilder)
	{
		// Normal OWIN pipeline setup here

		// Terminate the OWIN pipeline with a 404
		// This is needed b/c IIS starts a 2nd pipeline after the default pipeline terminating func is called.
		// This replaces the default pipeline terminating func.
		owinAppBuilder.Use(HandleNotFound);
	}

	/// <summary>
	/// Terminate the OWIN pipeline with a 404 response.
	/// </summary>
	/// <param name="owinRequestContext"></param>
	/// <param name="next"></param>
	/// <returns></returns>
	private Task HandleNotFound(IOwinContext owinRequestContext, Func<Task> next)
	{
		owinRequestContext.Response.StatusCode = 404;
		owinRequestContext.Response.ReasonPhrase = "URL not found";
		owinRequestContext.Response.ContentType = "text/plain";
		owinRequestContext.Response.ContentLength = 0;
		return Task.CompletedTask;
	}

}
```
